# Generated by Django 3.2.9 on 2023-06-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.TextField(max_length=100)),
                ('admin_pass', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'app_admin',
            },
        ),
    ]
