# Generated by Django 3.2.9 on 2023-07-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='admin_adress',
            field=models.TextField(default='Belirtilmemiş', max_length=400),
        ),
        migrations.AddField(
            model_name='admins',
            name='admin_email',
            field=models.TextField(default='Belirtilmemiş', max_length=400),
        ),
        migrations.AddField(
            model_name='admins',
            name='admin_insta',
            field=models.TextField(default='Belirtilmemiş', max_length=400),
        ),
        migrations.AddField(
            model_name='admins',
            name='admin_phone',
            field=models.IntegerField(default='Belirtilmemiş'),
        ),
        migrations.AddField(
            model_name='admins',
            name='admin_realname',
            field=models.TextField(default='Belirtilmemiş', max_length=400),
        ),
        migrations.AddField(
            model_name='admins',
            name='admin_surname',
            field=models.TextField(default='Belirtilmemiş', max_length=400),
        ),
        migrations.AddField(
            model_name='admins',
            name='admin_twitter',
            field=models.TextField(default='Belirtilmemiş', max_length=400),
        ),
    ]
