# Generated by Django 3.2.9 on 2023-07-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nedmin', '0003_auto_20230718_1642'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='admins',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='admins',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='password',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='username',
        ),
    ]
