# Generated by Django 3.2.9 on 2023-07-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedmin', '0004_auto_20230718_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='yazilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazi_baslik', models.TextField(max_length=100)),
                ('yazi_icerik', models.TextField(max_length=400)),
                ('dosya_yolu', models.FileField(upload_to='static/img')),
            ],
            options={
                'db_table': 'app_yazilar',
            },
        ),
    ]
