# Generated by Django 3.2.9 on 2023-07-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nedmin', '0006_auto_20230720_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yazilar',
            old_name='dosya_yolu',
            new_name='yazi_resim',
        ),
    ]
