# Generated by Django 3.2.9 on 2023-07-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nedmin', '0007_rename_dosya_yolu_yazilar_yazi_resim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yazilar',
            old_name='yazı_baslik',
            new_name='yazi_baslik',
        ),
        migrations.RenameField(
            model_name='yazilar',
            old_name='yazı_icerik',
            new_name='yazi_icerik',
        ),
    ]
