# Generated by Django 4.2.3 on 2023-07-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nedmin", "0008_auto_20230720_1642"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admins",
            name="admin_adress",
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name="admins",
            name="admin_email",
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name="admins",
            name="admin_insta",
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name="admins", name="admin_phone", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="admins",
            name="admin_realname",
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name="admins",
            name="admin_surname",
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name="admins",
            name="admin_twitter",
            field=models.TextField(max_length=400),
        ),
    ]
