# Generated by Django 4.2.3 on 2023-07-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nedmin", "0009_alter_admins_admin_adress_alter_admins_admin_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admins", name="admin_phone", field=models.BigIntegerField(),
        ),
    ]
