# Generated by Django 4.2.3 on 2023-07-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nedmin", "0010_alter_admins_admin_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admins",
            name="admin_adress",
            field=models.TextField(default="Belirtilmemiş", max_length=400),
        ),
        migrations.AlterField(
            model_name="admins",
            name="admin_email",
            field=models.TextField(default="Belirtilmemiş", max_length=400),
        ),
        migrations.AlterField(
            model_name="admins",
            name="admin_insta",
            field=models.TextField(default="Belirtilmemiş", max_length=400),
        ),
        migrations.AlterField(
            model_name="admins",
            name="admin_name",
            field=models.TextField(default="Belirtilmemiş", max_length=100),
        ),
        migrations.AlterField(
            model_name="admins",
            name="admin_pass",
            field=models.TextField(default="Belirtilmemiş", max_length=100),
        ),
        migrations.AlterField(
            model_name="admins", name="admin_phone", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="admins",
            name="admin_realname",
            field=models.TextField(default="Belirtilmemiş", max_length=400),
        ),
        migrations.AlterField(
            model_name="admins",
            name="admin_surname",
            field=models.TextField(default="Belirtilmemiş", max_length=400),
        ),
        migrations.AlterField(
            model_name="admins",
            name="admin_twitter",
            field=models.TextField(default="Belirtilmemiş", max_length=400),
        ),
    ]
